runtime: python310
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2

env_variables:
  FLASK_ENV: "production"

handlers:
  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico
  - url: /.*  # Catch-all for all routes
    script: auto
